set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
  CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASS' CREATEDB;
  GRANT CONNECT ON DATABASE postgres TO $APP_DB_USER;

  \c postgres

  GRANT SELECT ON ALL TABLES IN SCHEMA public TO $APP_DB_USER;
  REVOKE INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM $APP_DB_USER;

  ALTER DEFAULT PRIVILEGES FOR ROLE $APP_DB_USER GRANT SELECT ON TABLES TO $APP_DB_USER;
  ALTER DEFAULT PRIVILEGES FOR ROLE $APP_DB_USER REVOKE INSERT, UPDATE, DELETE ON TABLES FROM $APP_DB_USER;
EOSQL